services:

  user-service:
    image: microservices-user-service:latest

    build:
      context: ./user-service

    container_name: user-service

    restart: unless-stopped

    ports:
      - "3001:3001"

    networks:
      - microservice-network


  order-service:
    image: microservices-order-service:latest

    build:
      context: ./order-service

    container_name: order-service

    restart: unless-stopped

    ports:
      - "3002:3002"

    networks:
      - microservice-network


networks:
  microservice-network:
    driver: bridge