name: Microservices CI/CD

on:


  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      # -------------------------
      # 1. Checkout
      # -------------------------

      - name: Checkout code
        uses: actions/checkout@v4


      # -------------------------
      # 2. Setup SSH
      # -------------------------

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


      # -------------------------
      # 3. Install rsync
      # -------------------------

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync


      # -------------------------
      # 4. Copy project to EC2
      # -------------------------

      - name: Deploy files
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${{ secrets.SERVER_PORT }}" \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "node_modules" \
            ./ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/ubuntu/microservices-app/


      # -------------------------
      # 5. Build and start
      # -------------------------

      - name: Build and start containers
        run: |
          ssh \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -p ${{ secrets.SERVER_PORT }} \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

            cd /home/ubuntu/microservices-app

            docker compose down

            docker compose up -d --build

            docker image prune -f

            docker compose ps

          EOF